### ISSUE TITLE
Unplaced components

### ISSUE THREAD

**Issue by warmwaffles** [antmicro/scalenode#1]
I'm running KiCad 5.1.10 and I've also loaded this with a nightly build and see that there are some unplaced capacitors. Is this intentional?

PS. This is awesome

![20210501-104007](https://user-images.githubusercontent.com/303133/116787469-c3e84800-aa69-11eb-9490-db118abce304.png)

**Comment by pkatarzynski** [comment]
Hi warmwaffles

The design that was available on master was a WiP of the new PCB release. We have prototyped the release 1.0.0 in hardware and it worked pretty well. We are now adding some more tweaks to the new PCB revision.

I moved the current WiP work to the develop branch. The master branch is set to point to the last revision used for prototyping.
Thanks for spotting that.

**Comment by warmwaffles** [comment]
Awesome @pkatarzynski
